### PR TITLE
Update for check_file method

### PR DESCRIPTION
**Pull request by Mohammadreza-73**
Add file extension checker.

### CODE REVIEW

**Comment by Dictor** [comment]
It's good point out!

However, in my opinion, check error through `json_decode` is more better approach.
Following [official doc](https://www.php.net/manual/en/function.json-decode.php), this function return `null` when fail to decode. And error detail can be retrieved with `json_last_error`.

**Comment by donjajo** [comment]
File extensions do not determine the content of the file. @Dictor's approach looks like the better one IMO

**Comment by TomasVotruba** [comment]
Hi, I'm going through opened PRs as I'm using this amazing package.

I guess this can be closed then 👍

**Comment by donjajo** [comment]
Right. Thank you

**Comment by TomasVotruba** [comment]
Thanks for such a fast reply :+1: 

Btw, I'd like to contribute to this project, but I don't see any Github Actions CI or coding standards/static analysis. 
I think it would be big benefit for code maintenance and safer contributions from external devs.

Would you be interested in PR adding those?

**Comment by donjajo** [comment]
I am glad you found this helpful. I have not really been active over here.
I will appreciate your help in doing those.

Thank you very much

**Pull request closed without merging**
