### PR TITLE
return false on empty result

### PR DESCRIPTION
**Pull request by basteyy**
Add an boolean-false return in case no result was found

### CODE REVIEW

**Comment by Dictor** [comment]
It's good idea. However, there are a few things to keep in mind before merge it.
In my think, need to listen maintainer and user's opinion about this change.

### It may not be compatible with existing codes. See below example.
```php
$result = (some functions chain)->get();
if(count($result)) echo "No result!"; 
```
When result is empty, many existing code could check emptiness of result before and it's working well. But after applying this change, this method isn't working. (because count(false) is 1)
If decide to apply this change, careful version numbering is required for compatibility.

### Are multiple function return-types good practice?
Recent trend of php7 emphasize OOP. To meet this trend, explicit return declaration supporting is added. This means returning consistent type is more readable and easier to debug and develope. Of course it's controversial, but for simplicity and clarity, I think get() functions should return only array type.
In terms of convenience, there is no significant difference between `count($result) === 0` and `$result === false`.

**Comment by donjajo** [comment]
My exact thinking @Dictor :)

Lets stick to returning array, since in PHP
```
[] == false
[] == 0
[] !== false
[] !== 0
```
Lets stick to one return type.

**Comment by basteyy** [comment]
Change `public function get($false_on_empty = true)` to `public function get($false_on_empty = false)` will fix the problem with existing codes. Nevertheless adding a option the function seems to make sense to me. 

Are multiple function return-types good practice? Good point. I suggest a method in the function chain for casting the output somehow. And to follow practice, the function should trigger an exception, because the get function is called when there is data expected. This exception should be catched and handled. Perhaps a `function ()->exists();` is a better solution.

**Comment by donjajo** [comment]
```
$data = ..->get()
if( $data ) // This already does boolean check
if( count($data) ) // This too
```
Keep It Simple. Don't use OOP to complicate simple things, when talking of `()->exits();` when we can already do a conditional check on the returned data.

The change is not really necessary.

**Pull request closed without merging**
